export { LyricLintDatabase, closeDatabase, openDatabase } from './database.js';
export { createDraftRepository } from './draft-repository.js';
export { createMediaRepository } from './media-repository.js';
export type { MediaRepository } from './media-repository.js';
export { createWorkspaceBackup } from './backup.js';
export type { WorkspaceBackupController } from './backup.js';
export { createAutosaveController } from './autosave.js';
export { recoverStartupDraft } from './recovery.js';
export { createDraftIgnoreStore } from './draft-ignores.js';
export type { MediaHandleRecord, SessionStorageLike } from './types.js';
